# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pesel.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from  datetime import datetime


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        
        self.wagi = [1,3,7,9,1,3,7,9,1,3]
        self.dni = ["niedziela", "poniedziałek", "wtorek", "środa", "czwartek", "piątek", "sobota"]
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(536, 524)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEditPesel = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPesel.setMaxLength(11)
        self.lineEditPesel.setObjectName("lineEditPesel")
        self.verticalLayout.addWidget(self.lineEditPesel)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.listView = QtWidgets.QListWidget(self.centralwidget)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 536, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.pushButton.clicked.connect(self.sprawdzanie)
        self.pushButton_2.clicked.connect(self.zabij)
        
    def zabij(self):
        sys.exit(app.exec_())
        
    def sprawdzanie(self):
        self.pesel = self.lineEditPesel.text()
        if len(self.pesel)!= 11:
            self.listView.addItem("Błędna długość Peselu")
        else:
            self.listView.clear()
            suma = 0
            for p in range(len(self.pesel)-1):
                suma += int(self.pesel[p]) * self.wagi[p]
            m = 10-(suma % 10)
            
            if m == int(self.pesel[10]):
                self.listView.addItem("Pesel poprawny")
                p_year = self.pesel[:2]
                p_month = self.pesel[2:4]
                p_day = self.pesel[4:6]
                
                if self.pesel[2] in ['8','9']:
                    p_year = '18' + p_year
                if self.pesel[2] in ['0','1']:
                    p_year = '19' + p_year
                if self.pesel[2] in ['2','3']:
                    p_year = '20' + p_year
                if self.pesel[2] in ['4','5']:
                    p_year = '21' + p_year
                if self.pesel[2] in ['6','7']:
                    p_year = '22' + p_year
                
                if int(self.pesel[2]) in [8,2,4,6]:
                    p_month = '0' + self.pesel[3]
                elif int(self.pesel[2]) in [9,3,5,7]:
                    p_month = '1' + self.pesel[3]
                
                self.listView.addItem(f"Data urodzenia: {p_year}-{p_month}-{p_day}")
                
                data = datetime(year = int(p_year), month = int(p_month), day = int(p_day))
                dzien = data.toordinal() % 7
                self.listView.addItem(f"Dzień narodzin: {self.dni[dzien]}")
                
                if int(self.pesel[9]) % 2 == 0:
                    self.listView.addItem(f"Płeć: kobieta")
                else:
                    self.listView.addItem(f"Płeć: mężczyzna")
            
            else:
                self.listView.addItem("Pesel niepoprawny")
                       

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sprawdzanie Peselu"))
        self.pushButton.setText(_translate("MainWindow", "Sprawdź Pesel"))
        self.pushButton_2.setText(_translate("MainWindow", "Zamknij"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
